name: Build on Push
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 8.6.5

      - run: pnpm install --frozen-lockfile

      - run: npm run package --if-present

      - uses: actions/upload-artifact@v3
        with:
          name: Windows Executable
          path: build/*.exe

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: build/*.exe
